---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: localdev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  namespace: localdev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/gitea/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum-pv
  namespace: localdev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/chartmuseum/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  namespace: localdev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/docker-registry/
